name: Build and Deploy .NET App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' 

    - name: Build project
      working-directory: .NET  
      run: dotnet build

    - name: Publish project
      working-directory: .NET  
      run: dotnet publish -c Release -o out

    - name: Use secrets for environment variables
      env:
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      run: echo "Secrets set up completed"
